export const GOODS = {
  SET_ITEMS: 'GOODS:SET_ITEMS',
  SET_FILTRED_ITEMS: 'GOODS:SET_FILTRED_ITEMS',
  SET_FILTERNAME: 'GOODS:SET_FILTERNAME',
  SET_PART_ITEMS: 'GOODS:SET_PART_ITEMS',
  FILTER_BY_TITLE: 'GOODS:FILTER_BY_TITLE',
  DELETE_PART_FILTERED_ITEMS: 'GOODS:DELETE_PART_FILTERED_ITEMS',
  ADD_TAG: 'GOODS:ADD_TAG',
  DELETE_TAG: 'GOODS:DELETE_TAG',
  ADD_COLOR: 'GOODS:ADD_COLOR',
  DELETE_COLOR: 'GOODS:DELETE_COLOR',
  ADD_SIZE: 'GOODS:ADD_SIZE',
  DELETE_SIZE: 'GOODS:DELETE_SIZE',
  CHANGE_PRICE: 'GOODS:CHANGE_PRICE',
  SET_IS_LOADING: 'GOODS:SET_IS_LOADING',
  SET_VALUES_FROM_QUERIES: 'GOODS:SET_VALUES_FROM_QUERIES',
  RESET_FILTERS_AND_SORT: 'GOODS:RESET_FILTERS_AND_SORT',
}

export const PRODUCT = {
  SET_ITEMS: 'PRODUCT:SET_ITEMS',
  DELETE_ITEMS: 'PRODUCT:DELETE_ITEMS',
  SET_IS_LOADING: 'PRODUCT:SET_IS_LOADING',
}

export const THEME = {
  DARK_MODE: 'THEME:DARK_MODE',
}

export const PAGINATION = {
  SET_CURRENT_PAGE: 'PAGINATION:SET_CURRENT_PAGE',
}
