export const GOODS = {
  SET_ITEMS: 'GOODS:SET_ITEMS',
  SET_FILTERNAME: 'GOODS:SET_FILTERNAME',
  SET_PART_ITEMS: 'GOODS:SET_PART_ITEMS',
  FILTER_BY_TITLE: 'GOODS:FILTER_BY_TITLE',
  SET_IS_LOADING: 'GOODS:SET_IS_LOADING',
}

export const THEME = {
  DARK_MODE: 'THEME:DARK_MODE',
}

export const PAGINATION = {
  SET_CURRENT_PAGE: 'PAGINATION:SET_CURRENT_PAGE',
}
